# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/analyze_tracks_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(296, 619)
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(660, 470, 113, 64))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 5, 275, 590))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.track_id_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.track_id_lineEdit.setObjectName("track_id_lineEdit")
        self.gridLayout.addWidget(self.track_id_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mpp_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.mpp_doubleSpinBox.setObjectName("mpp_doubleSpinBox")
        self.gridLayout.addWidget(self.mpp_doubleSpinBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.fps_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.fps_doubleSpinBox.setObjectName("fps_doubleSpinBox")
        self.gridLayout.addWidget(self.fps_doubleSpinBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.max_lag_fit_spinBox = QtWidgets.QSpinBox(self.widget)
        self.max_lag_fit_spinBox.setObjectName("max_lag_fit_spinBox")
        self.gridLayout.addWidget(self.max_lag_fit_spinBox, 3, 1, 1, 1)
        self.error_term_checkBox = QtWidgets.QCheckBox(self.widget)
        self.error_term_checkBox.setObjectName("error_term_checkBox")
        self.gridLayout.addWidget(self.error_term_checkBox, 4, 0, 1, 1)
        self.batch_checkBox = QtWidgets.QCheckBox(self.widget)
        self.batch_checkBox.setObjectName("batch_checkBox")
        self.gridLayout.addWidget(self.batch_checkBox, 4, 1, 1, 1)
        self.go_pushButton = QtWidgets.QPushButton(self.widget)
        self.go_pushButton.setObjectName("go_pushButton")
        self.gridLayout.addWidget(self.go_pushButton, 5, 0, 1, 1)
        self.msd_graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.msd_graphicsView.setObjectName("msd_graphicsView")
        self.gridLayout.addWidget(self.msd_graphicsView, 6, 0, 1, 2)
        self.loglog_msd_graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.loglog_msd_graphicsView.setObjectName("loglog_msd_graphicsView")
        self.gridLayout.addWidget(self.loglog_msd_graphicsView, 7, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "track id"))
        self.label_2.setText(_translate("Dialog", "microns per pixel"))
        self.label_3.setText(_translate("Dialog", "frames per sec"))
        self.label_4.setText(_translate("Dialog", "max lagtime (fit)"))
        self.error_term_checkBox.setText(_translate("Dialog", "fit with error term"))
        self.batch_checkBox.setText(_translate("Dialog", "batch"))
        self.go_pushButton.setText(_translate("Dialog", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
